### ISSUE TITLE
[PE-D] Formatting error throughout User Guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-2/tp#155] opened 2022-04-01 16:22 UTC
Presence of "<&#47;br>" throughout the user guide which distracts readers and make some examples hard to understand
</br>![UG Bug.PNG](https://raw.githubusercontent.com/LowJiaHao99/ped/main/files/857e05fa-f29a-40e9-b6b7-d8bd77899a94.PNG)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: LowJiaHao99/ped#1

**Comment by cheehongw** [comment] 2022-04-04 12:37
duplicate of #173

**Comment by chriswengqi** [comment] 2022-04-04 12:39
#209

**Closed** 2022-04-04 14:06 UTC
Labels: duplicate, DocumentationBug, Medium
