### ISSUE TITLE
[PE-D] Duplicates of social media is not deleted

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-2/tp#193] opened 2022-04-01 17:42 UTC
![image.png](https://raw.githubusercontent.com/jessicajacelyn/ped/main/files/f8a41e53-34fb-462b-ba46-e8d35649658a.png)

because of the duplicate social media issue, not all @johndoe23 is deleted from the user detail, user will have to manually delete one-by-one.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: jessicajacelyn/ped#10

**Comment by cheehongw** [comment] 2022-04-04 14:41
duplicate of #187

**Closed** 2022-04-08 06:11 UTC
Labels: duplicate, Medium
