### ISSUE TITLE
[PE-D] </br> not applied correctly (UG)

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103-W16-2/tp#173] opened 2022-04-01 17:20 UTC
![Screenshot 2022-04-01 at 2.37.44 PM.png](https://raw.githubusercontent.com/viki0526/ped/main/files/a4358c24-967a-4aaf-b1b3-06e9c3e9f76e.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: viki0526/ped#3

**Comment by cheehongw** [comment] 2022-04-04 12:39
duplicate of #199

**Comment by reignnz** [comment] 2022-04-11 14:43
Fixed in PR #266

**Closed by reignnz** 2022-04-11 14:43 UTC
Labels: duplicate, DocumentationBug, Medium
